<?php

namespace App\Models;

use Illuminate\Support\Str;

/**
 * @property mixed $key
 * @property string $name
 * @property mixed $created_at
 * @property mixed $updated_at
 */
class ProductCategory extends BaseModel
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function (ProductCategory $category) {
            $categoryName = $category->name;
            $category->key = Str::of($categoryName)->slug('-');
            $category->name = Str::title($categoryName);
        });

        static::updated(function (ProductCategory $category) {
            $categoryName = $category->name;
            $category->key = Str::of($categoryName)->slug('-');
            $category->name = Str::title($categoryName);
        });
    }

    protected $fillable = [
        'name',
        'key'
    ];
}
